### ISSUE TITLE
Milestones organization

### ISSUE THREAD

**Issue by pdonorio** [mdantonio/rapydo#32]
A least of possible milestones to be checked:

- [ ] build templates (see [milestone n.2](https://github.com/mdantonio/rapydo/milestone/2))
- [ ] unittest standardization and complention
- [ ] packaging of rapydo and separated utils
- [ ] documentation for rapydo and vanilla projects...
- [ ] rapydo management script
